version: '3.7'
services:
  pg:
    image: postgres:16.2-alpine
    container_name: api-db
    restart: always
    environment:
      - 'POSTGRES_PASSWORD=hoplin1234!'
      - 'POSTGRES_DB=api'
      - 'TZ=Asia/Seoul'
    ports:
      - '5432:5432'
    networks:
      - network
networks:
  network:
    driver: bridge